# Generated by Django 4.0.5 on 2022-06-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('visits', models.IntegerField()),
                ('image', models.CharField(blank=True, default=None, max_length=2000, null=True)),
            ],
        ),
    ]
