# Generated by Django 4.0.5 on 2022-06-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_status_alter_checking_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='status',
            field=models.ManyToManyField(to='main_app.status'),
        ),
    ]
