# Generated by Django 4.0.5 on 2022-06-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_status_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='visits',
        ),
    ]
